require('vim._core.ui2').enable({
  enable = true,
  msg = {
    -- targets = 'cmd',
    targets = {
      -- [''] = 'cmd',
      empty = 'cmd',
      bufwrite = 'cmd',
      confirm = 'cmd',
      emsg = 'cmd',
      echo = 'cmd',
      echomsg = 'cmd',
      echoerr = 'cmd',
      completion = 'cmd',
      list_cmd = 'cmd',
      lua_error = 'cmd',
      lua_print = 'cmd',
      progress = 'msg',
      rpc_error = 'cmd',
      quickfix = 'cmd',
      search_cmd = 'cmd',
      search_count = 'cmd',
      shell_cmd = 'cmd',
      shell_err = 'cmd',
      shell_out = 'cmd',
      shell_ret = 'cmd',
      undo = 'cmd',
      verbose = 'cmd',
      wildlist = 'cmd',
      wmsg = 'cmd',
      typed_cmd = 'cmd',
    },
    cmd = {
      height = 0.35,
    },
    dialog = {
      height = 0.25,
    },
    msg = {
      height = 0.35,
      timeout = 5000,
    },
    pager = {
      height = 0.35,
    },
  },
})
