-- This code currently makes lspconfig do not work well

-- local cmp = require('cmp')
-- local sources = cmp.get_config().sources
-- for i = #sources, 1, -1 do
--   if sources[i].name == 'luasnip' then
--     table.remove(sources, i)
--   end
--
--   if sources[i].name == 'buffer' then
--     table.remove(sources, i)
--   end
--
--   if sources[i].name == 'marksman' then
--     table.remove(sources, i)
--   end
-- end
-- cmp.setup.buffer({ sources = sources })
