zstyle ':omz:plugins:nvm' lazy yes
zstyle ':omz:plugins:nvm' lazy-cmd eslint prettier typescript nvim copilot git gh node vim cdk npx zsh bash sh which nvim
zstyle ':omz:plugins:nvm' autoload no
zstyle ':omz:plugins:nvm' silent-autoload no # optionally remove the output generated by NVM when autoloading
