alias vf='vifm .'
alias remote='~/.config/bin/remote.sh'
# alias neomutt='(TERM=xterm-direct neomutt) 2>/dev/null'
alias lsa='lsd -la'
alias tks='tmux kill-server'
alias tms=tmux-sessionizer
alias tn='tmux new -s (pwd | sed '\''s/.*\///g'\'')'
alias tt='~/.config/bin/tt.sh'
alias gc='~/.config/bin/gcbare.sh'
alias clear=''
alias gop='git open'
alias cat='bat --paging=never'
alias k='kubectl'
alias dc='docker-compose'
