export PATH="$HOME/.config/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$PATH:/opt/nvim:$PATH"
export PATH="$PATH:$HOME/.fzf/bin:$PATH"
export DYLD_LIBRARY_PATH="/opt/homebrew/opt/girara/lib:$DYLD_LIBRARY_PATH"
