return {
  {
    "nvim-tree/nvim-web-devicons",
    lazy = true,
    -- cmd = { "NvimTreeToggle", "NvimTreeFocus", "NvimTreeFindFile" },
    -- lazy = true,
    -- priority = 800,
    opts = {
      override = {
        sql = {
          icon = "",
          name = "sql",
          color = "#9CDCFE",
        },
        pptx = {
          icon = "󱎐",
          name = "ppxpowerpiont",
          color = "#8ee2cf",
        },
        http = {
          icon = "",
          name = "http",
          color = "#9CDCFE",
        },
        yml = {
          icon = "󰘧",
          color = "#9CDCFE",
          name = "yml",
        },
        png = {
          icon = "",
          color = "#CBA6F7",
          name = "png",
        },
        yaml = {
          icon = "󰘧",
          color = "#9CDCFE",
          name = "yaml",
        },
        dot = {
          icon = "󱁉",
          color = "#9CDCFE",
          name = "puntodot",
        },
        html = {
          icon = "",
          name = "html",
          -- color = "#C24C38",
          color = "#F38BA8",
        },
        dockerfile = {
          icon = "",
          color = "#9CDCFE",
          name = "Dockerfile4",
        },
        groovy = {
          icon = "",
          name = "groovyfile",
        },
        [".npmignore"] = {
          icon = "",
          color = "#7C7F93",
          name = "npmignore",
        },
        [".npmrc"] = {
          icon = "",
          color = "#F38BA8",
          name = "npmrc1",
        },
        ["out"] = {
          icon = "",
          color = "#F38BA8",
          cterm_color = "124",
          name = "Out",
        },
        zsh = {
          icon = "",
          color = "#9CDCFE",
          cterm_color = "65",
          name = "Zsh",
        },
        ["scss"] = {
          icon = "󰟬",
          color = "#F38BA8",
          name = "scss1",
        },

        ["xlsx"] = {
          icon = "󰈛",
          color = "#73daca",
          name = "xlsx1",
        },
        ["csv"] = {
          icon = "",
          color = "#9CDCFE",
          name = "Csv",
        },
        ["md"] = {
          icon = "",
          color = "#9CDCFE",
          name = "Markdown2",
        },
        json = {
          icon = "󰘦",
          name = "json",
          color = "#9CDCFE",
        },
        java = {
          icon = "",
          name = "java",
          -- color = "#9CDCFE",
          color = "#F38BA8",
        },
        gradle = {
          icon = "",
          name = "gradle",
          color = "#89B4FA",
        },
        bat = {
          -- icon = "",
          icon = "",
          name = "bat",
          color = "#CBA6F7",
        },
        js = {
          icon = "",
          name = "javascript",
          color = "#F5E0DC",
        },
        ["cjs"] = {
          icon = "",
          color = "#F5E0DC",
          name = "Cjs",
        },
        ["mjs"] = {
          icon = "",
          color = "#F5E0DC",
          name = "mjs1",
        },
        pdf = {
          icon = "",
          name = "pdf1",
          color = "#F38BA8",
        },
        txt = {
          icon = "󰈚",
          name = "txtname",
          color = "#8ee2cf",
        },
        toml = {
          icon = "",
          name = "toml",
          color = "#737aa2",
        },
        zip = {
          icon = "",
          name = "zipp",
          color = "#F5E0DC",
        },
        ["CODEOWNERS"] = { icon = "󱖨", color = "#73daca", name = "codeownersfile1" },
        ["d.ts"] = {
          -- icon = "",
          icon = "󰛦",
          -- color = "#F38BA8",
          -- color = "#CBA6F7",
          color = "#89B4FA",
          -- cterm_color = "172",
          name = "TypeScriptDeclaration",
        },
        default_icon = {
          -- icon = "󰙄",
          -- icon = "󰈤",
          -- icon = "🀄️",
          icon = "",
          -- icon = "🀀",
          -- icon = "",
          -- icon = "",
          -- icon = "",
          -- icon = "",
          -- icon = "",
          -- icon = "📄",
          -- icon = "",
          -- color = "#73daca",
          -- color = "grey",
          -- color = "#7C7F93",
          color = "#89ddff",
          name = "DefaultIcon",
        },
      },
      color_icons = true,
      default = false,
      strict = false,
      override_by_filename = {
        [".zshrc"] = {
          icon = "",
          color = "#7C7F93",
          name = "zshrc",
        },
        [".envrc"] = {
          icon = "",
          color = "#F2CDCD",
          name = "Envrc1",
        },

        ["tmux.conf"] = { icon = "", color = "#9CDCFE", name = "tmuxconf1" },
        ["docker-compose.yml"] = { icon = "󰡨", color = "#9CDCFE", name = "DockerComposeYml" },
        ["docker-compose.yaml"] = { icon = "󰡨", color = "#9CDCFE", name = "DockerComposeYml2" },
        [".dockerignore"] = { icon = "", color = "#9CDCFE", name = "DockerfileIgnore" },
        ["Dockerfile"] = { icon = "", color = "#9CDCFE", name = "Dockerfile2" },
        ["dockerfile"] = { icon = "", color = "#9CDCFE", name = "Dockerfile5" },
        ["app.routes.ts"] = { icon = "󰑪", color = "#73daca", name = "AngularRoutes" },
        ["webpack.config.js"] = { icon = "󰜫", color = "#9CDCFE", name = "WebpackConfig" },
        ["README.md"] = { icon = "", color = "#9CDCFE", name = "readmemd" },
        [".gitattributes"] = { icon = "󰊢", color = "#f38bad", name = "gitattributes" },
        ["LICENSE"] = { icon = "", color = "#f38bad", name = "licensefile" },
        [".gitignore"] = { icon = "󰊢", color = "#7C7F93", name = "gitignore" },
        [".git"] = { icon = "󰊢", color = "#CA9EE6", name = "giticonworktree" },
        ["readme.md"] = { icon = "", color = "#9CDCFE", name = "readmemd1" },
        ["webpack.prod.config.js"] = { icon = "󰜫", color = "#9CDCFE", name = "WebpackConfigProd" },
        ["webpack.config.ts"] = { icon = "󰜫", color = "#9CDCFE", name = "WebpackConfigTS" },
        ["webpack.prod.config.ts"] = { icon = "󰜫", color = "#9CDCFE", name = "WebpackConfigProdTS" },
        ["package.json"] = { icon = "", color = "#73daca", name = "PackageJson" },
        [".package.json"] = { icon = "", color = "#73daca", name = "PackageJson1" },
        ["*.package.json"] = { icon = "", color = "#73daca", name = "PackageJson2" },
        ["*package.json"] = { icon = "", color = "#73daca", name = "PackageJson3" },
        ["package-lock.json"] = { icon = "", color = "#73daca", name = "PackageLockJson" },
        ["pnpm-lock.yaml"] = { icon = "", color = "#F5E0DC", name = "pnpmLockYaml" },
        ["favicon.ico"] = { icon = "", color = "#F5E0DC", name = "faviconico" },
        ["codeowners"] = { icon = "󱖨", color = "#73daca", name = "codeownersfile2" },
        ["jenkinsfile"] = { icon = "", name = "Jenkins8", color = "#c0caf5" },
        ["jenkinsfileci"] = { icon = "", name = "Jenkins3", color = "#c0caf5" },
        ["jenkinsfilecd"] = { icon = "", name = "Jenkins4", color = "#c0caf5" },
        ["JenkinsfileCD"] = { icon = "", name = "Jenkins5", color = "#c0caf5" },
        ["JenkinsfileCI"] = { icon = "", name = "Jenkins7", color = "#c0caf5" },
        ["jest.config.ts"] = { icon = "󰙨", name = "jenkinsconfig1", color = "#f38bad" },
        ["jest.config.app.ts"] = { icon = "󰙨", name = "jenkinsconfigapp1", color = "#f38bad" },
        ["jest.config.js"] = { icon = "󰙨", name = "jenkinsconfig2", color = "#f38bad" },
        ["sonar-project.properties"] = { icon = "󰐷", color = "#CBA6F7", name = "sonarproperties" },
        ["nx.json"] = { icon = "󰰔", color = "#9CDCFE", name = "nxjson" },
        [".nxignore"] = { icon = "󰰔", color = "#7C7F93", name = "nxignore" },
        [".eslintignore"] = { icon = "󰱺", color = "#7C7F93", name = "eslintignore" },
        ["eslint.config.js"] = { icon = "󰱺", color = "#9CDCFE", name = "eslintconfigjs" },
        ["eslint.config.ts"] = { icon = "󰱺", color = "#9CDCFE", name = "eslintconfigts" },
        ["eslint.config.mjs"] = { icon = "󰱺", color = "#9CDCFE", name = "eslintconfigmjs" },
        [".eslintrc.json"] = { icon = "󰱺", color = "#9CDCFE", name = "eslintrcjson" },
        [".eslintrc.base.json"] = { icon = "󰱺", color = "#9CDCFE", name = "eslintrcbasejson" },
        [".eslint-report.json"] = { icon = "󰱺", color = "#9CDCFE", name = "eslintreportjson" },
        [".actrc"] = { icon = "", color = "#CBA6F7", name = "actrc" },
        ["commitlint.config.ts"] = { icon = "󰜘", color = "#CBA6F7", name = "commitlintconfig12" },
        [".prettierignore"] = { icon = "", color = "#7C7F93", name = "prettierignore" },
        [".prettierrc"] = { icon = "", color = "#73daca", name = "prettierrc" },
        [".prettierrc.json"] = { icon = "", color = "#73daca", name = "prettierrcjson" },
        ["project.json"] = { icon = "", color = "#9CDCFE", name = "ProjectJson" },
        ["tsconfig.federation.json"] = {
          icon = "󰛦",
          color = "#9CDCFE",
          name = "TSDeclarationfile23",
        },
        ["gradlew"] = {
          icon = "",
          name = "gradlew",
          color = "#89B4FA",
        },
        ["application.properties"] = { icon = "", color = "#CBA6F7", name = "application_properties" },
        ["tsconfig.json"] = { icon = "󰛦", color = "#9CDCFE", name = "TSDeclarationfile2" },
        ["tsconfig.editor.json"] = { icon = "󰛦", color = "#9CDCFE", name = "TSDeclarationfile2" },
        ["tsconfig.base.json"] = { icon = "󰛦", color = "#9CDCFE", name = "TSDeclarationfile2" },
        ["tsconfig.app.json"] = { icon = "󰛦", color = "#9CDCFE", name = "TSDeclarationfile1" },
        ["tsconfig.lib.json"] = { icon = "󰛦", color = "#9CDCFE", name = "TSDeclarationfile1" },
        ["tsconfig.spec.json"] = { icon = "󰛦", color = "#9CDCFE", name = "TSDeclarationfile1" },
        ["mvnw"] = { icon = "", color = "#f38ba8", name = "mvnw" },
        ["mvnw.cmd"] = { icon = "", color = "#f38ba8", name = "mvnw.cmd" },
        ["pom.xml"] = { icon = "", color = "#f38ba8", name = "pomxml" },
        ["settings.gradle"] = {
          icon = "",
          color = "#89B4FA",
          cterm_color = "24",
          name = "GradleSettings",
        },
        ["build.gradle"] = {
          icon = "",
          color = "#89B4FA",
          cterm_color = "24",
          name = "GradleBuildScript",
        },
        ["gradle.properties"] = {
          icon = "",
          color = "#89B4FA",
          cterm_color = "24",
          name = "GradleProperties",
        },
        ["gradle-wrapper.properties"] = {
          icon = "",
          color = "#89B4FA",
          cterm_color = "24",
          name = "GradleWrapperProperties",
        },
        [".factorypath"] = {
          icon = "󰗀",
          color = "#f38ba8",
          name = ".classpath",
        },
        [".classpath"] = {
          icon = "󰗀",
          color = "#f38ba8",
          name = ".classpath",
        },
        [".project"] = {
          icon = "󰗀",
          color = "#f38ba8",
          name = ".classpath",
        },
        ["CODE_OF_CONDUCT.md"] = { icon = "", color = "#f38bad", name = "codeofconduct" },
        ["NOTICE"] = { icon = "", color = "#CBA6F7", name = "notice" },
      },
      override_by_extension = {
        [".env"] = {
          icon = "",
          color = "#F2CDCD",
          name = "Env2",
        },
        ["log"] = {
          icon = "",
          color = "#73daca",
          name = "Log",
        },
        ["module.ts"] = { icon = "", color = "#CBA6F7", name = "AngularModule1" },
        ["*.module.ts"] = { icon = "", color = "#CBA6F7", name = "AngularModule2" },
        [".module.ts"] = { icon = "", color = "#CBA6F7", name = "AngularModule" },
        ["service.ts"] = { icon = "", color = "#F5E0DC", name = "AngularService1" },
        [".service.ts"] = { icon = "", color = "#F5E0DC", name = "AngularService2" },

        ["component.ts"] = { icon = "󰚿", color = "#89b4fa", name = "AngularComponent1" },

        ["routes.ts"] = { icon = "󰑪", color = "#73daca", name = "AngularRoutesFile" },
        [".routes.ts"] = { icon = "󰑪", color = "#73daca", name = "AngularRoutesFile" },
        ["*.routes.ts"] = { icon = "󰑪", color = "#73daca", name = "AngularRoutesFile" },

        ["angular.json"] = { icon = "󰚿", color = "#f38ba8", name = "AngularJson" },
        ["*angular.json"] = { icon = "󰚿", color = "#f38ba8", name = "AngularJson" },
        ["*.angular.json"] = { icon = "󰚿", color = "#f38ba8", name = "AngularJson" },
        [".angular.json"] = { icon = "󰚿", color = "#f38ba8", name = "AngularJson" },
        ["directive.ts"] = { icon = "", color = "#6f32a8", name = "AngularDirective" },
        ["*.directive.ts"] = { icon = "", color = "#6f32a8", name = "AngularDirective" },
        [".directive.ts"] = { icon = "", color = "#6f32a8", name = "AngularDirective" },
        [".stories.ts"] = { icon = "", color = "#f55385", name = "Storie1" },
        ["stories.ts"] = { icon = "", color = "#f55385", name = "Storie2" },
        ["bun.lockb"] = { icon = "", color = "#F5C2E7", name = "bunlock" },
        ["codeowners"] = { icon = "󱖨", color = "#73daca", name = "codeownersfile3" },
        [".editorconfig"] = { icon = "", color = "#c0caf5", name = "Editorconfig" },
        ["drawio"] = { icon = "󰇟", color = "#F5E0DC", name = "drawio1" },
        ["sql"] = { icon = "", color = "#9CDCFE", name = "sqlextension" },
        ["spec.js"] = {
          icon = "",
          color = "#9CDCFE",
          name = "SpecJs",
        },
        ["spec.ts"] = {
          icon = "",
          color = "#9CDCFE",
          name = "SpecTs",
        },
        ["test.js"] = {
          icon = "",
          color = "#9CDCFE",
          name = "TestJs",
        },
        ["test.ts"] = {
          icon = "",
          color = "#9CDCFE",
          name = "SpecJs",
        },
      },
    },
  },
}
