return {
	{
		"Mirsmog/real-icons.nvim",
		enabled = false,
		build = ":RealIconsInstallPack material",
		opts = {
			pack = "material",
			integrations = {
				telescope = true,
				oil = true,
			},
		},
	},
	{
		"nvim-tree/nvim-web-devicons",
		lazy = true,
		opts = {
			override = {
				isyncrc = {
					icon = "󱋈",
					name = "isyncrc",
					color = "#9CDCFE",
				},
				keys = {
					icon = "",
					name = "keys",
					color = "#F5C2E7",
				},
				mfd = {
					icon = "󰘸",
					name = "mfd",
					color = "#CBA6F7",
				},
				nfc = {
					icon = "󰎘",
					name = "nfc",
					color = "#9CDCFE",
				},
				ics = {
					icon = "",
					name = "ics",
					color = "#CBA6F7",
				},
				css = {
					icon = "",
					name = "css",
					color = "#9CDCFE",
				},
				heic = {
					icon = "",
					name = "heic",
					color = "#CBA6F7",
				},
				bin = {
					icon = "",
					name = "bin",
					color = "#f38bad",
				},
				ipa = {
					icon = "",
					name = "ipa",
					color = "#94E2D5",
				},
				apk = {
					icon = "",
					name = "Apk",
					color = "#94E2D5",
				},
				swift = {
					icon = "",
					name = "swift",
					color = "#FAB387",
				},
				xml = {
					icon = "󰗀",
					name = "xml",
					color = "#f38bad",
				},
				storyboard = {
					icon = "",
					name = "storyboard",
					color = "#9CDCFE",
				},
				plist = {
					icon = "",
					name = "plist",
					color = "#9CDCFE",
				},
				xcworkspacedata = {
					icon = "",
					name = "xcworkspacedata",
					color = "#9CDCFE",
				},
				pbxproj = {
					icon = "",
					name = "pbxproj",
					color = "#9CDCFE",
				},
				rake = {
					icon = "",
					name = "rake",
					color = "#f38bad",
				},
        gem = {
          icon = "",
          name = "gem",
          color = "#f38bad",
        },
				gemspec = {
					icon = "",
					name = "gemspec",
					color = "#f38bad",
				},
				rb = {
					icon = "",
					name = "rb",
					color = "#f38bad",
				},
        ["ruby-version"] = {
          icon = "",
          name = "rubyversion",
          color = "#f38bad",
        },
				ruby = {
					icon = "",
					name = "ruby",
					color = "#f38bad",
				},
				scpt = {
					icon = "",
					name = "applescript2",
					color = "#9CDCFE",
				},
				tsx = {
					icon = "",
					name = "tsx",
					color = "#9CDCFE",
				},
				jsx = {
					icon = "",
					name = "jsx",
					color = "#9CDCFE",
				},
				mov = {
					icon = "",
					name = "mov",
					color = "#94E2D5",
				},
				lock = {
					icon = "󰈡",
					name = "lock",
					color = "#7C7F93",
				},
				gz = {
					icon = "",
					name = "zip",
					color = "#F5C2E7",
				},
				zip = {
					icon = "",
					name = "zip",
					color = "#F2CDCD",
				},
				mp3 = {
					icon = "",
					name = "mp3",
					color = "#F5C2E7",
				},
				docx = {
					icon = "󰈬",
					name = "docx",
					color = "#9CDCFE",
				},
				sql = {
					icon = "",
					name = "sql",
					color = "#9CDCFE",
				},
				pptx = {
					icon = "󱎐",
					name = "ppxpowerpiont",
					color = "#8ee2cf",
				},
				hurl = {
					icon = "",
					name = "hurl",
					color = "#F5BDE6",
				},
				http = {
					icon = "",
					name = "http",
					color = "#9CDCFE",
				},
				yml = {
					icon = "󰘧",
					color = "#9CDCFE",
					name = "yml",
				},
				png = {
					icon = "",
					color = "#CBA6F7",
					name = "png",
				},
				yaml = {
					icon = "󰘧",
					color = "#9CDCFE",
					name = "yaml",
				},
				dot = {
					icon = "󱁉",
					color = "#9CDCFE",
					name = "puntodot",
				},
				html = {
					icon = "",
					name = "html",
					-- color = "#C24C38",
					color = "#F38BA8",
				},
				dockerfile = {
					icon = "",
					color = "#9CDCFE",
					name = "Dockerfile4",
				},
				groovy = {
					icon = "",
					name = "groovyfile",
				},
				[".npmignore"] = {
					icon = "",
					color = "#7C7F93",
					name = "npmignore",
				},
				[".npmrc"] = {
					icon = "",
					color = "#F38BA8",
					name = "npmrc1",
				},
				["out"] = {
					icon = "",
					color = "#F38BA8",
					cterm_color = "124",
					name = "Out",
				},
				zsh = {
					icon = "",
					color = "#9CDCFE",
					cterm_color = "65",
					name = "Zsh",
				},
				["scss"] = {
					icon = "󰟬",
					color = "#F38BA8",
					name = "scss1",
				},

				["xlsx"] = {
					icon = "󰈛",
					color = "#73daca",
					name = "xlsx1",
				},
				["csv"] = {
					icon = "",
					color = "#9CDCFE",
					name = "Csv",
				},
				["md"] = {
					icon = "",
					-- icon = "",
					-- icon = "",
					-- icon = "",
					-- icon = "",
					-- color = "#9CDCFE",
					color = "#F5C2E7",
					name = "Markdown2",
				},
				json = {
					icon = "󰘦",
					name = "json",
					color = "#9CDCFE",
				},
				java = {
					icon = "",
					name = "java",
					-- color = "#9CDCFE",
					color = "#F38BA8",
				},
				gradle = {
					icon = "",
					name = "gradle",
					color = "#89B4FA",
				},
				h = {
					icon = "",
					-- icon = "H",
					name = "h",
					color = "#9CDCFE",
				},
				c = {
					-- icon = "󰙱",
					icon = "",
					name = "c",
					color = "#9CDCFE",
				},
				bat = {
					-- icon = "",
					icon = "",
					name = "bat",
					color = "#CBA6F7",
				},
				js = {
					-- icon = "",
					icon = "",
					name = "javascript",
					color = "#F5E0DC",
				},
				["cjs"] = {
					icon = "",
					color = "#F5E0DC",
					name = "Cjs",
				},
				["rspec"] = {
					icon = "",
					color = "#F38BA8",
					name = "rspec",
				},
				["mjs"] = {
					icon = "",
					color = "#F5E0DC",
					name = "mjs1",
				},
				pdf = {
					icon = "",
					name = "pdf1",
					color = "#F38BA8",
				},
				txt = {
					icon = "󰈚",
					name = "txtname",
					color = "#8ee2cf",
				},
				toml = {
					icon = "",
					name = "toml",
					color = "#737aa2",
				},
				["CODEOWNERS"] = { icon = "󱖨", color = "#73daca", name = "codeownersfile1" },
				-- ["ts"] = {
				-- 	-- icon = "",
				-- 	icon = "텗",
				-- 	-- color = "#F38BA8",
				-- 	-- color = "#CBA6F7",
				-- 	color = "#89B4FA",
				-- 	-- cterm_color = "172",
				-- 	name = "TypeScriptDeclaration",
				-- },
				-- ["ts"] = {
				--   icon = "",
				--   -- icon = "󰛦",
				--   	-- icon = "텗",
				--   -- color = "#F38BA8",
				--   -- color = "#CBA6F7",
				--   color = "#89ddff",
				--   -- cterm_color = "172",
				--   name = "typescript",
				-- },
				["d.ts"] = {
					-- icon = "",
					-- icon = "󰛦",
					icon = "텗",
					-- color = "#F38BA8",
					-- color = "#CBA6F7",
					color = "#89B4FA",
					-- cterm_color = "172",
					name = "TypeScriptDeclaration",
				},
				["ts.map"] = {
					icon = "텗",
					color = "#89B4FA",
					-- cterm_color = "172",
					name = "typescriptmap",
				},
				default_icon = {
					-- icon = "󰙄",
					-- icon = "󰈤",
					-- icon = "🀄️",
					-- icon = "",
					icon = "",
					-- icon = "🀀",
					-- icon = "",
					-- icon = "",
					-- icon = "",
					-- icon = "",
					-- icon = "",
					-- icon = "📄",
					-- icon = "",
					-- color = "#73daca",
					-- color = "grey",
					-- color = "#7C7F93",
					color = "#89ddff",
					name = "DefaultIcon",
				},
			},
			color_icons = true,
			default = false,
			strict = false,
			override_by_filename = {
				[".env.default"] = {
					icon = "",
					color = "#F2CDCD",
					name = "EnvFile2",
				},
				[".env.release"] = {
					icon = "",
					color = "#F2CDCD",
					name = "EnvFile3",
				},
				[".zshrc"] = {
					icon = "",
					color = "#7C7F93",
					name = "zshrc",
				},
				[".envrc"] = {
					icon = "",
					color = "#F2CDCD",
					name = "Envrc1",
				},

				["tmux.conf"] = { icon = "", color = "#9CDCFE", name = "tmuxconf1" },
				[".sdkmanrc"] = { icon = "", color = "#7C7F93", name = "sdkman" },
				["docker-compose.yml"] = { icon = "󰡨", color = "#9CDCFE", name = "DockerComposeYml" },
				["docker-compose.yaml"] = { icon = "󰡨", color = "#9CDCFE", name = "DockerComposeYml2" },
				[".dockerignore"] = { icon = "", color = "#7C7F93", name = "DockerfileIgnore" },
				["Dockerfile"] = { icon = "", color = "#9CDCFE", name = "Dockerfile2" },
				["dockerfile"] = { icon = "", color = "#9CDCFE", name = "Dockerfile5" },
				["app.routes.ts"] = { icon = "󰑪", color = "#73daca", name = "AngularRoutes" },
				["webpack.config.js"] = { icon = "󰜫", color = "#9CDCFE", name = "WebpackConfig" },
				[".gitmodules"] = { icon = "", color = "#f38bad", name = "gitattributes" },
				[".gitattributes"] = { icon = "󰊢", color = "#f38bad", name = "gitattributes" },
				["LICENSE"] = { icon = "", color = "#f38bad", name = "licensefile" },
				[".gitignore"] = { icon = "󰊢", color = "#7C7F93", name = "gitignore" },
				[".stow-local-ignore"] = { icon = "", color = "#7C7F93", name = "stowglobal" },
				[".stow-global-ignore"] = { icon = "", color = "#7C7F93", name = "stowglobal" },
				[".git"] = { icon = "󰊢", color = "#CA9EE6", name = "giticonworktree" },
				[".gitconfig"] = { icon = "", color = "#CA9EE6", name = "giticonworktree" },
				[".luacheckrc"] = { icon = "", color = "#9CDCFE", name = "luacheckrc" },
				["readme.md"] = { icon = "", color = "#CA9EE6", name = "readmemd1" },
				-- ["readme.md"] = { icon = "", color = "#9CDCFE", name = "readmemd1" },
				-- ["readme.md"] = { icon = "", color = "#9CDCFE", name = "readmemd1" },
				["webpack.prod.config.js"] = { icon = "󰜫", color = "#9CDCFE", name = "WebpackConfigProd" },
				["webpack.config.prod.ts"] = { icon = "󰜫", color = "#9CDCFE", name = "WebpackConfigProdTS" },
				["webpack.config.ts"] = { icon = "󰜫", color = "#9CDCFE", name = "WebpackConfigTS" },
				["webpack.prod.config.ts"] = { icon = "󰜫", color = "#9CDCFE", name = "WebpackConfigProdTS" },

				[".bash_profile"] = { icon = "", color = "#73daca", name = "bash_profile" },
				[".bashrc"] = { icon = "", color = "#73daca", name = "bashrc" },
				[".zprofile"] = { icon = "", color = "#73daca", name = "zprofile" },
				[".zshenv"] = { icon = "", color = "#73daca", name = "zshenv" },
				[".vimrc"] = { icon = "", color = "#73daca", name = "vimrc2323" },

				["vitest.config.js"] = { icon = "", color = "#73daca", name = "vitest_config_js" },
				["Fastfile"] = { icon = "", color = "#f38bad", name = "fastfile" },
				["Gymfile"] = { icon = "", color = "#f38bad", name = "fastfile" },
				-- ["package.json"] = { icon = "", color = "#73daca", name = "PackageJson" },
				-- [".package.json"] = { icon = "", color = "#73daca", name = "PackageJson1" },
				-- ["*.package.json"] = { icon = "", color = "#73daca", name = "PackageJson2" },
				-- ["*package.json"] = { icon = "", color = "#73daca", name = "PackageJson3" },
				-- ["package-lock.json"] = { icon = "", color = "#73daca", name = "PackageLockJson" },
				["yarn.lock"] = { icon = "", color = "#c0caf5", name = "yarnlock" },
				["capacitor.config.json"] = { icon = "", color = "#9CDCFE", name = "capacitorconfig" },
				["package.json"] = { icon = "", color = "#73daca", name = "PackageJson" },
				[".package.json"] = { icon = "", color = "#73daca", name = "PackageJson1" },
				["*.package.json"] = { icon = "", color = "#73daca", name = "PackageJson2" },
				["*package.json"] = { icon = "", color = "#73daca", name = "PackageJson3" },
				["package-lock.json"] = { icon = "", color = "#73daca", name = "PackageLockJson" },

				["pnpm-lock.yaml"] = { icon = "", color = "#F5E0DC", name = "pnpmLockYaml" },
				["favicon.ico"] = { icon = "", color = "#F5E0DC", name = "faviconico" },
				["codeowners"] = { icon = "󱖨", color = "#73daca", name = "codeownersfile2" },
				["jenkinsfile"] = { icon = "", name = "Jenkins8", color = "#c0caf5" },
				["jenkinsfileci"] = { icon = "", name = "Jenkins3", color = "#c0caf5" },
				["jenkinsfilecd"] = { icon = "", name = "Jenkins4", color = "#c0caf5" },
				["JenkinsfileCD"] = { icon = "", name = "Jenkins5", color = "#c0caf5" },
				["JenkinsfileCI"] = { icon = "", name = "Jenkins7", color = "#c0caf5" },
				["jest.config.cts"] = { icon = "", name = "jenkinsconfigcts1", color = "#f38bad" },
				["jest.config.ts"] = { icon = "", name = "jenkinsconfig1", color = "#f38bad" },
				["jest.config.app.ts"] = { icon = "", name = "jenkinsconfigapp1", color = "#f38bad" },
				["jest.config.js"] = { icon = "", name = "jenkinsconfig2", color = "#f38bad" },
				["sonar-project.properties"] = { icon = "󰐷", color = "#CBA6F7", name = "sonarproperties" },
				["nx.json"] = { icon = "", color = "#c0caf5", name = "nxjson" },
				[".nxignore"] = { icon = "", color = "#7C7F93", name = "nxignore" },
				[".eslintignore"] = { icon = "󰱺", color = "#7C7F93", name = "eslintignore" },
				["eslint.config.js"] = { icon = "󰱺", color = "#9CDCFE", name = "eslintconfigjs" },
				["eslint.config.ts"] = { icon = "󰱺", color = "#9CDCFE", name = "eslintconfigts" },
				["eslint.config.mjs"] = { icon = "󰱺", color = "#9CDCFE", name = "eslintconfigmjs" },
				["eslint.config.cjs"] = { icon = "󰱺", color = "#9CDCFE", name = "eslintconfigcjs" },
				[".eslintrc.json"] = { icon = "󰱺", color = "#9CDCFE", name = "eslintrcjson" },
				[".eslintrc.base.json"] = { icon = "󰱺", color = "#9CDCFE", name = "eslintrcbasejson" },
				[".eslint-report.json"] = { icon = "󰱺", color = "#9CDCFE", name = "eslintreportjson" },
				[".actrc"] = { icon = "", color = "#CBA6F7", name = "actrc" },
				["commitlint.config.ts"] = { icon = "󰜘", color = "#CBA6F7", name = "commitlintconfig12" },
				[".prettierignore"] = { icon = "", color = "#7C7F93", name = "prettierignore" },
				["prettier.config.js"] = { icon = "", color = "#73daca", name = "prettierconfigjs" },
				["prettier.config.ts"] = { icon = "", color = "#73daca", name = "prettierconfigts" },
				[".prettierrc"] = { icon = "", color = "#73daca", name = "prettierrc" },
				[".prettierrc.json"] = { icon = "", color = "#73daca", name = "prettierrcjson" },
				["project.json"] = { icon = "", color = "#9CDCFE", name = "ProjectJson" },
				["babel.config.json"] = { icon = "", color = "#F5E0DC", name = "babelconfig" },
				[".babelrc"] = { icon = "", color = "#F5E0DC", name = "babelrc" },
				["gradlew"] = {
					icon = "",
					name = "gradlew",
					color = "#89B4FA",
				},
				["Pluginfile"] = { icon = "", color = "#f38bad", name = "fastfile" },
				["Rakefile"] = { icon = "", color = "#f38ba8", name = "rakefile" },
				["Podfile"] = { icon = "", color = "#f38ba8", name = "podfile" },
				["Podfile.lock"] = { icon = "", color = "#7C7F93", name = "podfilelock2" },
				["Gemfile"] = { icon = "", color = "#f38ba8", name = "gemfilefile" },
				["Gemfile.lock"] = { icon = "", color = "#7C7F93", name = "gemfilelock" },
				["application.properties"] = { icon = "", color = "#CBA6F7", name = "application_properties" },
				["tsconfig.federation.json"] = {
					icon = "󰛦",
					-- icon = "텗",
					color = "#9CDCFE",
					name = "TSDeclarationfile23",
				},
				["tsconfig.lib.prod.json"] = {
					-- icon = "텗",
					-- icon = "",
					icon = "󰛦",
					color = "#9CDCFE",
					name = "tslibprodjson2",
				},
				["tsconfig.json"] = {
					-- icon = "텗",
					-- icon = "",
					icon = "󰛦",
					color = "#9CDCFE",
					name = "TSDeclarationfile2",
				},
				["tsconfig.editor.json"] = {
					icon = "󰛦",
					-- icon = "텗",
					-- icon = "",
					color = "#9CDCFE",
					name = "TSDeclarationfile2",
				},
				["tsconfig.base.json"] = {
					icon = "󰛦",
					-- icon = "텗",
					-- icon = "",
					color = "#9CDCFE",
					name = "TSDeclarationfile2",
				},
				["tsconfig.app.json"] = {
					icon = "󰛦",
					-- icon = "텗",
					-- icon = "",
					color = "#9CDCFE",
					name = "TSDeclarationfile1",
				},
				["tsconfig.lib.json"] = {
					icon = "󰛦",
					-- icon = "텗",
					-- icon = "",
					--      icon = "텘",
					color = "#9CDCFE",
					name = "TSDeclarationfile1",
				},
				["tsconfig.spec.json"] = {
					icon = "󰛦",
					-- icon = "텗",
					-- icon = "",
					color = "#9CDCFE",
					name = "TSDeclarationfile1",
				},
				["mvnw"] = { icon = "", color = "#f38ba8", name = "mvnw" },
				["mvnw.cmd"] = { icon = "", color = "#f38ba8", name = "mvnw.cmd" },
				["pom.xml"] = { icon = "", color = "#f38ba8", name = "pomxml" },
				["settings.gradle"] = {
					icon = "",
					color = "#89B4FA",
					cterm_color = "24",
					name = "GradleSettings",
				},
				["build.gradle"] = {
					icon = "",
					color = "#89B4FA",
					cterm_color = "24",
					name = "GradleBuildScript",
				},
				["gradle.properties"] = {
					icon = "",
					color = "#89B4FA",
					cterm_color = "24",
					name = "GradleProperties",
				},
				["gradle-wrapper.properties"] = {
					icon = "",
					color = "#89B4FA",
					cterm_color = "24",
					name = "GradleWrapperProperties",
				},
				[".factorypath"] = {
					icon = "󰗀",
					color = "#f38ba8",
					name = ".classpath",
				},
				[".classpath"] = {
					icon = "󰗀",
					color = "#f38ba8",
					name = ".classpath",
				},
				[".project"] = {
					icon = "󰗀",
					color = "#f38ba8",
					name = ".classpath",
				},
				["CODE_OF_CONDUCT.md"] = { icon = "", color = "#f38bad", name = "codeofconduct" },
				["NOTICE"] = { icon = "", color = "#CBA6F7", name = "notice" },
			},
			override_by_extension = {
				["swcrc"] = {
					icon = "",
					color = "#F5E0DC",
					name = "swcrcfile",
				},
				[".nvmrc"] = {
					icon = "",
					color = "#73daca",
					name = "nvmrcfile",
				},
        [".env.dev"] = {
          icon = "",
          color = "#F2CDCD",
          name = "Env25",
        },
				[".env"] = {
					icon = "",
					color = "#F2CDCD",
					name = "Env23",
				},
				["env"] = {
					icon = "",
					color = "#F2CDCD",
					name = "Env23",
				},
				["log"] = {
					icon = "",
					color = "#73daca",
					name = "Log",
				},
				["xcconfig"] = { icon = "", color = "#9CDCFE", name = "xcconfigfile" },
				["module.ts"] = { icon = "", color = "#CBA6F7", name = "AngularModule1" },
				["*.module.ts"] = { icon = "", color = "#CBA6F7", name = "AngularModule2" },
				[".module.ts"] = { icon = "", color = "#CBA6F7", name = "AngularModule" },
				["service.ts"] = { icon = "", color = "#F5E0DC", name = "AngularService1" },
				[".service.ts"] = { icon = "", color = "#F5E0DC", name = "AngularService2" },

				["component.ts"] = { icon = "󰚿", color = "#89b4fa", name = "AngularComponent1" },

				["routes.ts"] = { icon = "󰑪", color = "#73daca", name = "AngularRoutesFile" },
				[".routes.ts"] = { icon = "󰑪", color = "#73daca", name = "AngularRoutesFile" },
				["*.routes.ts"] = { icon = "󰑪", color = "#73daca", name = "AngularRoutesFile" },

				["angular.json"] = { icon = "󰚿", color = "#f38ba8", name = "AngularJson" },
				["*angular.json"] = { icon = "󰚿", color = "#f38ba8", name = "AngularJson" },
				["*.angular.json"] = { icon = "󰚿", color = "#f38ba8", name = "AngularJson" },
				[".angular.json"] = { icon = "󰚿", color = "#f38ba8", name = "AngularJson" },
				["directive.ts"] = { icon = "", color = "#CBA6F7", name = "AngularDirective" },
				["*.directive.ts"] = { icon = "", color = "#CBA6F7", name = "AngularDirective" },
				[".directive.ts"] = { icon = "", color = "#CBA6F7", name = "AngularDirective" },
				[".stories.ts"] = { icon = "", color = "#f55385", name = "Storie1" },
				["stories.ts"] = { icon = "", color = "#f55385", name = "Storie2" },
				-- ["bun.lockb"] = { icon = "", color = "#F5C2E7", name = "bunlock" },
				[".bun-version"] = {
					icon = "",
					color = "#EADCD1",
					cterm_color = "253",
					name = "BunLockfile",
				},
				["codeowners"] = { icon = "󱖨", color = "#73daca", name = "codeownersfile3" },
				[".editorconfig"] = { icon = "", color = "#c0caf5", name = "Editorconfig" },
				["drawio"] = { icon = "󰇟", color = "#F5E0DC", name = "drawio1" },
				["sql"] = { icon = "", color = "#9CDCFE", name = "sqlextension" },
				["spec.js"] = {
					-- icon = "",
					icon = "󰂓",
					color = "#9CDCFE",
					name = "SpecJs",
				},
				["spec.ts"] = {
					-- icon = "",
					icon = "󰂓",
					color = "#9CDCFE",
					name = "SpecTs",
				},
				["test.js"] = {
					-- icon = "",
					icon = "󰂓",
					color = "#9CDCFE",
					name = "TestJs",
				},
				["test.ts"] = {
					-- icon = "",
					icon = "󰂓",
					color = "#9CDCFE",
					name = "SpecJs",
				},
			},
		},
	},
}
